apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - headless-service.yaml
  - game-server-node-services.yaml
  - game-server-ingress.yaml
  - deployment.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml
  - mysql.yaml
  - redis.yaml
