apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: game-server
  namespace: actiongame
  labels:
    app.kubernetes.io/name: game-server
    app.kubernetes.io/part-of: actiongame
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: actiongame-server
